apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-with-sec-vol
  namespace: "${{ values.namespace }}"
  labels:
    app: "${{ values.app }}"
spec:
  replicas: "${{ values.replicas }}"
  selector:
    matchLabels:
      app: "${{ values.app }}"
  template:
    metadata:
      labels:
        app: "${{ values.app }}"
    spec:
      containers:
      - name: pod-with-sec
        image: nginx
        volumeMounts:
        - name: sec-vol
          mountPath: /home/secvol
      volumes:
      - name: sec-vol
        secret:
          secretName: secret-test1
